apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: web-terminal
  namespace: openshift-operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: web-terminal
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: 2.operators/web-terminal
    repoURL: https://github.com/danielpenagos/rh1-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true