---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: rhsso-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: devspaces-lab-sso
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: 2.operators/rhsso
    repoURL: https://github.com/danielpenagos/rh1-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
    - CreateNamespace=true
